### ISSUE TITLE
CORS only Access-Control-Allow-Origin * accepted

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/cordova-plugin-wkwebview-engine#7] opened 2016-08-19 07:34 UTC
Hi,

Thank for the plugin. Really easy to integrate and it really improves the performance.

But, unfortunately, I face a CORS problem. I noticed that only requests where Access-Control-Allow-Origin set to * could be performed and are accepted/working.

For test purpose, I changed my server request header to * and was then able to use my application correctly with my server. But to be honest, I don't think that's a proper solution. Furthermore I also use the Yelp API V3 in my application, where the Access-Control-Allow-Origin is also not set to * (and they said they won't change it). So even if I change my server, I will still have a problem in another places in my application.

Is there then a way to fix that problem? 

I tried WKWebView with other plugins before and faced the same problem, here what I documented on the Ionic forum.

https://forum.ionicframework.com/t/wkwebview-and-ionic2-proxy/59614

Or is there a way to bypass that problem with a proxy maybe ?

Thx in advance

**Comment by jgw96** [comment] 2016-08-19 14:19
Hello! Thanks for opening an issue with us! I will be closing this issue as a duplicate of https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/3. Thanks for using Ionic!

**Closed by jgw96** 2016-08-19 14:19 UTC
