### ISSUE TITLE
Access-Control-Allow-Origin Error

### ISSUE THREAD

**Issue by tanzl88** [driftyco/cordova-plugin-wkwebview-engine#109] opened 2017-03-21 03:48 UTC
Http requests failed after updated to v3.0. I received 
`Failed to load resource: Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin.` 
in console. Somehow the request origin is localhost:8080. Is this intended? I also updated CLI to v3.

![screen shot 2017-03-21 at 11 46 24 am](https://cloud.githubusercontent.com/assets/4703671/24131868/21e4bb66-0e2c-11e7-950e-91b475a85a14.png)

Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.0 
    ios-sim version: 3.1.1 
    OS: OS X El Capitan
    Node Version: v6.10.0
    Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by awebdeveloper** [comment] 2017-03-22 17:08
You could allow cors to localhost (though it would not be recommend)

Duplicate of https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/111

**Closed** 2017-04-08 14:27 UTC
