### ISSUE TITLE
XHR's fail with invalid or self-signed SSL certificates

### ISSUE THREAD

**Issue by bostondv** [driftyco/cordova-plugin-wkwebview-engine#46] opened 2016-09-09 19:53 UTC
Making HTTPS requests using WKWebView fail when the remote server uses a self-signed SSL certificate. 

```
Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “dev.myapiserver.com” which could put your confidential information at risk
```

For a production build of an app this isn't be a problem, but during development self-signed certificates are common and as far as I can tell there's no configuration to allow insecure certificates?

Is there a workaround or possible to fix within the scope of this plugin?

**Comment by mhartington** [comment] 2016-09-09 20:40
Could you provide what version of iOS you are seeing this on?  This appears to be an issue on iOS 8, but could still be an issue with newer iOS as well. 


Some resources 
http://stackoverflow.com/questions/27100540/allow-unverified-ssl-certificates-in-wkwebview/32507262#32507262

**Comment by bostondv** [comment] 2016-09-09 20:47
Sorry, I'm seeing it on iOS 9.3 (iPhone 6S Plus Simulator). Built with Xcode 7.3.1.

I browsed through that and some other similar resources before posting. I'm definitely not getting any challenge dialog asking to accept the insecure cert.

**Comment by bostondv** [comment] 2016-09-09 22:07
After more testing I realized this isn't specific to WKWebView.

In UIWebView, my app was working around it by using Cordova Certificate plugin: https://github.com/hypery2k/cordova-certificate-plugin. But this plugin doesn't work in WKWebView.

Regardless, would be great if there was a way to allow invalid certs in WKWebView without other plugins.

**Comment by manucorporat** [comment] 2016-09-12 15:39
@bostondv  there is in fact a way:
https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKNavigationDelegate_Ref/index.html#//apple_ref/occ/intfm/WKNavigationDelegate/webView:didReceiveAuthenticationChallenge:completionHandler:

but I am not sure it is responsibility of this plugin to implement it but another plugin, such as `cordova-certificate-plugin`

**Comment by manucorporat** [comment] 2016-09-12 17:31
ping @hypery2k

**Comment by hypery2k** [comment] 2016-09-12 18:44
feel free to open up an issue for this, but currently I'm busy with other stuff, so may take a while

**Comment by bostondv** [comment] 2016-09-12 18:56
Will do, thanks @manucorporat @hypery2k 

I'm no Obj-C expert, but may take a stab at implementing it.

**Comment by hypery2k** [comment] 2016-09-13 03:45
The problem is not the objective C part, the effort comes from make the plugin recognize which WebView is used ;)

**Comment by manucorporat** [comment] 2016-09-14 14:56
I am going to close this issue since this feature should be fulfilled by another plugin.

@hypery2k I might try to contribute to your plugin, but it is low priority right now ;)

**Closed by manucorporat** 2016-09-14 14:56 UTC

**Comment by ghenry22** [comment] 2017-02-20 04:23
@hypery2k why not allow the user to specify webview as an argument sent to the plugin as there are ways of determining the webview in use on the javascript side.  This could also potentially deal with incorporating crosswalk support as the dev should be able to specify and then the native component doesn't have to detect and switch automatically.

**Comment by hypery2k** [comment] 2017-02-20 07:45
great idea. But currently to have time for this, but any PR is welcome

**Comment by ghenry22** [comment] 2017-05-16 00:40
@manucorporat as the certificate plugin hasn't been updated in quite some time and looks like the maintainer has minimal time to dedicate to it these days I think this should be re-opened and built into the wkwebview plugin.

The ionic branch of this plugin is now actually useful and well beyond the original cordova core plugin, one persistent issue that I have though is that many of my app users connect to a server that uses a self signed certificate, which means I am getting a lot of support requests about it not working and have to ask people to use unencrypted connections instead which many don't like.  There is no way to easily get a valid cert on the server side as the server is run on peoples home NAS or computer or cloud account.  The value is in the encrypted transport not the identity confirmation.

Could a similar acceptunsigned(true/false) method be added to the wkwebview plugin which would be false by default but all users to enable if their app needs it.

I would love to be able to contribute a PR but it's a bit above my pay grade unfortunately!
